### ISSUE TITLE
cannot open bot.ml page

### ISSUE THREAD

**Issue by lijiarui** [wechaty/bot5.ml#224]
It showed a blank page when open bot.ml

![image](https://user-images.githubusercontent.com/6419514/120332809-ac7ad400-c321-11eb-9bec-e4186a0a7417.png)

**Comment by huan** [comment]
Fixed by re-deploy the whole site by pushing another commit.

It seems that the GitHub pages have some issues recently, wechaty.js.org has a similar issue this month too.
